# Generated by Django 4.2.5 on 2023-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
                ('Payment', models.CharField(choices=[('C', 'CreditCard'), ('D', 'DebitCard'), ('P', 'Paypal')], max_length=1)),
                ('NameOnCard', models.CharField(blank=True, max_length=50, null=True)),
                ('CardNumber', models.IntegerField(blank=True, null=True)),
                ('Expiration', models.CharField(blank=True, max_length=50, null=True)),
                ('CVV', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
