# Generated by Django 4.2.5 on 2023-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='CategoryName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
