# Generated by Django 4.2.5 on 2023-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0003_productdb_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
